---
- name: Install core packages
  become: true
  community.general.pacman:
    name:
      - git
      - neovim
      - alacritty
      - rofi
      - thunar
      - dunst
      - picom
      - flameshot
      - arandr
      - tree
      - eza
      - tldr
      - thefuck
      - xclip
      - alsa-utils
      - sl
      - nftables
      - base-devel
      - ripgrep
      - tmux
      - lazygit
      - docker
      - docker-buildx
    state: present
