---
# Symlink system configs that need to live outside $HOME
- name: Symlink nftables.conf to /etc/
  become: true
  when: ansible_facts['os_family'] == "Archlinux"
  ansible.builtin.file:
    src: "{{ ansible_facts['env']['HOME'] }}/.config/nftables.conf"
    dest: /etc/nftables.conf
    state: link
    force: true
  notify: Restart nftables

- name: Enable nftables
  become: true
  when: ansible_facts['os_family'] == "Archlinux"
  ansible.builtin.systemd:
    name: nftables
    enabled: true
