#!/usr/sbin/nft -f

table inet filter
delete table inet filter

table inet filter {
    chain input {
        type filter hook input priority filter; policy drop;
        ct state invalid drop comment "early drop of invalid connections"
        ct state { established, related } accept comment "allow tracked connections"
        iif "lo" accept comment "allow from loopback"
        meta l4proto { icmp, ipv6-icmp } accept comment "allow icmp"
        tcp dport 22 accept comment "allow sshd"
        tcp dport { 80, 443 } accept
        tcp dport { 25, 465 } accept
        tcp dport 8096 accept comment "jellyfin"
        udp dport 7359 accept comment "jellyfin discovery"
    }
    chain output {
        type filter hook output priority filter; policy accept;
    }
    # No forward chain - Docker manages forwarding via its own nftables tables
}
