#!/usr/sbin/nft -f

table ip my_filter
delete table ip my_filter

table ip my_filter {
     chain input {
          type filter hook input priority filter; policy drop;
          ct state established,related accept
          iif "lo" accept
          tcp dport 22 accept
          tcp dport { 80, 443 } accept
          tcp dport { 25, 465 } accept
          tcp dport 8096 accept # jellyfin
          udp dport 7359 accept # jellyfin
      }
      chain forward {
          type filter hook forward priority filter - 1; policy accept;

          # Let Docker manage forwarding via its own table.
      }
      chain output {
          type filter hook output priority filter; policy accept;
      }
  }
