# Default colors
[colors.primary]
background = '#222222'
foreground = '#fbf8ff'

# Normal colors
[colors.normal]
black   = '#363537'
red     = '#fc618d'
green   = '#7bd88f'
yellow  = '#fce566'
blue    = '#fd9353'
magenta = '#948ae3'
cyan    = '#5ad4e6'
white   = '#f7f1ff'

# Bright colors
[colors.bright]
black   = '#69676c'
red     = '#fc618d'
green   = '#7bd88f'
yellow  = '#fce566'
blue    = '#fd9353'
magenta = '#948ae3'
cyan    = '#5ad4e6'
white   = '#f7f1ff'
